config/routes.rb
Rails.application.routes.draw do
  
  get 'shelters/index'

  resources :shelters
  resources :cats
  resources :dogs
  root 'welcome#index'
end

app/models/pet.rb
class Pet < ActiveRecord::Base
	
zip_code = [ 10001..10040, 10044, 10048, 10065, 10069, 10075, 10111, 10115, 10128, 10280, 
10282, 11201, 11203..11226, 11228..11239, 11251, 11001, 11004, 11005, 11040, 11096, 
11101..11106, 11109, 11354..11369, 11371..11375, 11378, 11379, 11385, 11411..11422, 
11426..11430, 11432..11436, 11451, 11691, 11692, 11694, 11697, 10451..10462, 10465..10475, 
10301..10314 ]

def location
	@location = zip_code
	if @zip_code == true
		return zip_code
	else
		puts "Please enter a valid New York City zip code, or choose by borough"
end

app/models/shelter.rb
class Shelter < ActiveRecord::Base

zip_code = [ "10001".."10040", "10044", "10048", "10065", "10069", "10075", "10111", "10115", "10128", "10280", 
"10282", "11201", "11203".."11226", "11228".."11239", "11251", "11001", "11004", "11005", "11040", "11096", 
"11101".."11106", "11109", "11354".."11369", "11371".."11375", "11378", "11379", "11385", "11411".."11422", 
"11426".."11430", "11432".."11436", "11451", "11691", "11692", "11694", "11697", "10451".."10462", "10465".."10475", 
"10301".."10314" ]


def location
	@location = zip_code
	if @zip_code == true
		return zip_code
	else
		puts "Please enter a valid New York City zip code, or choose by borough"
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
	# before_action :petfinder_api

	def index
		@cats = petfinder.find_pets('cat', ZIPCODE, count: 100)
		# @breeds = petfinder.breeds('cat')

		# count = params[:count] ? params[:count] : 100 

		# @location = zip_code
  		# @shelters = petfinder.find_shelters(params[:zipcode], count: params[:count])  #params[:zip_code])

		# @shelters = petfinder.find_shelters('11217', count: params[:count])  #params[:zip_code])

  		#@pets = petfinder.find_pets('dog', "10002", count: 25)
	end

  	def show
  		@cat = petfinder.pet(params[:id])
  		# @anything_pet = petfinder_api
  		# petfinder = petfinder_api
  		# @pets = petfinder.find_pets('dog', '11235')
  		# # @this_pet = petfinder.pet('23749930').photos.first.thumbnail
  		# @this_pet = petfinder.pet('23749930').photos
  	end

private
	def petfinder
		Petfinder::Client.new('688ee530a00d023570937d905bc9fc3c', 'cbe668e242d17b16fee3e6ac17769c8c')
	end	
end
	

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
	# before_action :petfinder_api

	def index
		@dogs = petfinder.find_pets('dog', ZIPCODE, count: 100)
		# @breeds = petfinder.breeds('cat')

		# count = params[:count] ? params[:count] : 100 

		# @location = zip_code
  		# @shelters = petfinder.find_shelters(params[:zipcode], count: params[:count])  #params[:zip_code])

		# @shelters = petfinder.find_shelters('11217', count: params[:count])  #params[:zip_code])

  		#@pets = petfinder.find_pets('dog', "10002", count: 25)
	end

  	def show
  		@dog = petfinder.pet(params[:id])
  		# @anything_pet = petfinder_api
  		# petfinder = petfinder_api
  		# @pets = petfinder.find_pets('dog', '11235')
  		# # @this_pet = petfinder.pet('23749930').photos.first.thumbnail
  		# @this_pet = petfinder.pet('23749930').photos
  	end

private
	def petfinder
		Petfinder::Client.new('688ee530a00d023570937d905bc9fc3c', 'cbe668e242d17b16fee3e6ac17769c8c')
	end	
end
	

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController
  	before_action :petfinder_api


  def index
	petfinder = petfinder_api
	shelters = petfinder.find_shelters(zip_code, count: 25)

  end

  def shelter_params
    params.require(:shelter).permit(:zip_code)
  end


private
	def petfinder_api
		Petfinder::Client.new('688ee530a00d023570937d905bc9fc3c', 'cbe668e242d17b16fee3e6ac17769c8c')
	end	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/cats/_cats.html.erb
<% if @user.errors.full_messages.any? %>
<ul>
	<% @user.errors.full_messages.each do |message| %>
	<li><%= message %></li>
	<% end %>
</ul>
<% end %>

<% form_for @cat do method: :post |f| %>
	<% end %>

app/views/cats/index.html.erb
<h1>All Pets in New York City</h1>



<p>Below is a list of cats!</p>
<ul>
	<% @cats.each do |cat| %>
		<li>
			<img src=<%= cat.photos.first.small unless cat.photos.empty? %> alt="">
			<%= cat.name %>
			<%= link_to 'See this pet!', cat_path(cat.id) %>
		</li>
	<% end %>
</ul>

<!-- <p>Age of pet is </p>

<p></p> -->

app/views/cats/show.html.erb
<h1>Here is the cat you clicked on!</h1>

<h2><%= @cat.name %></h2>


<% @cat.photos.each do |photo| %>
	<img src=<%= photo.large %> alt="">
<% end %>

<!-- iterate over the photos!-->

<p><%= @cat.breeds %></p>
<p><%= @cat.age %></p>
<p><%= @cat.sex %></p>
<p><%= @cat.size %></p>
<p><%= @cat.shelter_id %></p>
<p><%= @cat.status %></p>
<p><%= @cat.description %></p>
<p><%= @cat.contact %></p>




<% if false %>
	<ul><% @pets.each do |pet| %>
		<li><img src=<%= @anything_pet.pet(pet.id).photos.first.small %> alt=""></li>
		<% end %>
	</ul>	

	<h2><%= @this_pet %></h2>
<% end %>

app/views/dogs/_dogs.html.erb
<% if @user.errors.full_messages.any? %>
<ul>
	<% @user.errors.full_messages.each do |message| %>
	<li><%= message %></li>
	<% end %>
</ul>
<% end %>

<% form_for @dog do method: :post |f| %>
	<% end %>

app/views/dogs/index.html.erb
<h1>All Pets in New York City</h1>



<p>Below is a list of dogs!</p>
<ul>
	<% @dogs.each do |dog| %>
		<li>
			<img src=<%= dog.photos.first.small unless dog.photos.empty? %> alt="">
			<%= dog.name %>
			<%= link_to 'See this pet!', dog_path(dog.id) %>
		</li>
	<% end %>
</ul>

<!-- <p>Age of pet is </p>

<p></p> -->

app/views/dogs/new.html.erb
<h1>Pets#new</h1>
<p>Find me in app/views/pets/new.html.erb</p>

app/views/dogs/show.html.erb
<h1>Here is the dog you clicked on!</h1>

<h2><%= @dog.name %></h2>


<% @dog.photos.each do |photo| %>
	<img src=<%= photo.large %> alt="">
<% end %>

<!-- iterate over the photos!-->

<p><%= @dog.breeds %></p>
<p><%= @dog.age %></p>
<p><%= @dog.sex %></p>
<p><%= @dog.size %></p>
<p><%= @dog.shelter_id %></p>
<p><%= @dog.status %></p>
<p><%= @dog.description %></p>
<p><%= @dog.contact %></p>




<% if false %>
	<ul><% @pets.each do |pet| %>
		<li><img src=<%= @anything_pet.pet(pet.id).photos.first.small %> alt=""></li>
		<% end %>
	</ul>	

	<h2><%= @this_pet %></h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PetfinderNyc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= flash[:notice] if flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/shelters/index.html.erb
<h1>Shelters#index</h1>
<p>Find me in app/views/shelters/index.html.erb</p>


<p> all shelters in <%= @location %>
	<ul><% @shelters.each do |shelter| %>
		<li><%= shelter %></li>
		<% end %>
	</ul>

app/views/welcome/index.html.erb
<h1>Forever Home-NYC</h1>

<p>Button goes here for "Click for Cats"<p>
<p>Button goes here for "Click for Dogs"<p>